addons:
  hosts:
  - node1
before_install:
- rvm reload
- rvm use 2.4.2 --install
- nvm install 8.9.3
- nvm use 8.9.3
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.rvm
  - $NVM_DIR
dist: trusty
env:
- MODULES=storm-client
- MODULES=storm-server
- MODULES=storm-core
- MODULES='!storm-client,!storm-server,!storm-core'
- MODULES='INTEGRATION-TEST'
install: /bin/bash ./dev-tools/travis/travis-install.sh `pwd`
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- /bin/bash ./dev-tools/travis/travis-script.sh `pwd` $MODULES
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: required
